name: test-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
    install:
      tailscale
      zsh
      git
      mpd
      ncmpcpp
      tmux
      btop
    remove:

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        io.gitlab.news_flash.NewsFlash
        com.nextcloud.desktopclient.nextcloud
        md.obsidian.Obsidian
        com.spotify.Client
        tv.plex.PlexDesktop
        org.kde.konsole
        io.github.zen_browser.zen
      remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

